sources = {
	'investing_v0' : {'xpath_article' : '//section[@id="leftColumn"]/div[@class="WYSIWYG articlePage"]//text()'},
	'investing_v1' : {'xpath_article' : '//div[@class="arial_14 clear WYSIWYG newsPage"]/p/text()'},
	'investing_v2' : {'xpath_article' : '//section[@id="leftColumn"]/node()/p/text()'},
	'reuters' : {'xpath_article' : '//div[@class="StandardArticleBody_container"]/div[@class="StandardArticleBody_body"]/p//text()'},
	'fxempire' : {'xpath_article' : '//div[@class="grid__ColSystem-s18zed6k-7 cOzXed Col-jCOnJH eucWXp"]/node()/node()//text()'},	
	'fxempire_2' : {'xpath_article' : '//article[@class="Post__PostArticle-s1czihrw-0 hWBjOF"]/node()/node()/node()//text()'},
	'talkmarkets' : {'xpath_article' : '//div[@id="content"]/div[@class="card"]/div[@class="tm-article_card-block"]/div[@id="blog-content"]//text()'},
	'fxstreet' : {'xpath_article' : '//article[@class="fxs_article"]/div[@class="fxs_row sticky-holder"]/div[@class="fxs_flex_col"]/div[@class="fxs_article_body"]//text()'},
	'stocknewsjournal' : {'xpath_article' : '//div[@class="td-pb-row"]/div[@class="td-pb-span8 td-main-content"]/div[@class="td-ss-main-content"]/node()/div[@class="td-post-content"]/p//text()'},
	'briefing' : {'xpath_article' : '//div[@id="content"]/div[@class="story-wrapper"]/div[@class="summary-wrapper"]/div[2]//text()'},
	'livemint' : {'xpath_article' : '//section[@class="left-sidebar"]/div[@class="content-box"]/div[@class="clearfix"]/div[@class="content"]/p//text()'},
	'forexlive' : {'xpath_article' : '//div[@class="article-main-container"]/node()/div[@class="container-fluid"]/div[@class="row pad-top10"]/node()//text()'},
	'dailyfx' : {'xpath_article' : '//article/div[@class="article-body article-body-img article_page"]/div[@class="story_body"]/div[@class="story_paragraph"]/p//text()'},
	'marketpulse' : {'xpath_article' : '//section[@class="col-a left"]/node()/div[@class="contents"]/p//text()'},
	'foxbusiness' : {'xpath_article' : '//article[@class="story"]/div[@class="inner"]/div[@class="article-content content article-body"]/div[@class="article-text"]/p//text()'},
	'ecb_europa' : {'xpath_article' : '//main/div[@class="ecb-pressContent"]/article/p//text()'},
	'nasdaq' : {'xpath_article' : '//div[@id="content"]/div[@id="left-column-div"]/div[@id="articlebody"]/div[@id="articleText"]/p//text()'},
	'investopedia' : {'xpath_article' : '//article/div[@class="content-box"]/p//text()'},
	'equities' : {'xpath_article' : '//div[@class="item-page"]/div[@id="articleBody"]/p//text()'},
	'fool' : {'xpath_article' : '//div[@id="wrapper"]/article[@class="large-8 columns clearfix"]/section[@id="full_content"]/p//text()'},
	'pymnts' : {'xpath_article' : '//div[@id="post-left-col"]/article[@id="post-area"]/div[@id="content-area"]/div[@class="post-cont-out"]/div[@class="post-cont-in"]/div[@id="content-main"]/p//text()'},
	'marketwatch' : {'xpath_article' : '//article[@id="article"]/div[@id="article-meat"]/div[@id="article-body"]/p//text()'},
	'euroexchangeratenews' : {'xpath_article' : '//div[@class="cwc-main"]/div[@class="cwc-row"]/main[@class="cwc-content"]/article/section[@class="entry-content"]/p//text()'},
}

